version: 2
jobs:
  build:
    working_directory: ~/repo
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'

